### ISSUE TITLE
Declaring fields

### ISSUE THREAD

**Issue by mcpotter** [jtribe/java-code-styles#3]
Do we want to allow this sort of syntax? 

`private int measurementSelection = 0, typeSelection = 0;`

Or do we want it to always be one line/field?

**Comment by simonexmachina** [comment]
I don't mind. I've used both forms over the years. I prefer to be able to be expressive with that kind of thing, so I vote yes. Anyone else have an opinion?

**Comment by AngusMorton** [comment]
I prefer one field declaration per line because I think it's more readable. The reason I brought it up in the PR was because it was a bit jarring for me as the reviewer, especially in a codebase where multiple field declarations on a single line is not commonplace.

For what it's worth, Google also follow this guideline: https://google.github.io/styleguide/javaguide.html#s4.8.2.1-variables-per-declaration

**Comment by simonexmachina** [comment]
Okay great. If the code style's not clear on that point then we should update it. @mcpotter can you do this if necessary please.

**Comment by mcpotter** [comment]
Done.
